version: '3'
services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - db
  db:
    image: mongo
  