version: '3.5'
services:

  frontend-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-app
      - /frontend-app/node_modules
    links:
      - db
      - backend-app
  
  backend-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python -u app/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - db
  
  db:
    build: 
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/testdata:/testdata
   
  helge-api:
    build: 
      context: ./helge-api
      dockerfile: Dockerfile
    command: python -u app/api.py
    ports:
      - "5001:5001"
    volumes:
      - ./helge-api:/app
    links:
      - backend-app
    

