version: '3.5'
services:

  helge-api:
    image: hnclonecphb/http-api
    environment:
      - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq:5672/rabbitmq_vhost
    ports:
      - 5001:5001
    links:
      - backend-app
      - database  
      - rabbitmq
    networks:
      - hackernews_ops

  frontend-app:
    image: hnclonecphb/frontend
    ports:
      - 3000:3000
    links:
      - database
      - backend-app
    networks:
      - hackernews_ops
  
  backend-app:
    image: hnclonecphb/backend:master
    ports:
      - 5000:5000
    links:
      - database
    networks:
      - hackernews_ops

  database:
    image: hnclonecphb/database
    networks:
      - hackernews_ops

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq_vhost
    ports:
      - 5672:5672
    networks:
      - hackernews_ops

networks:
  hackernews_ops:
    name: hackernews_ops
    driver: bridge
