version: '3.5'
services:

  frontend-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-app
      - /frontend-app/node_modules
    links:
      - backend-app
  
  backend-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python -u app/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - database
  
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/testdata:/testdata
   
  helge-api:
    build: 
      context: ./helge-api
      dockerfile: Dockerfile
    command: python -u app/api.py
    environment: 
      - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq:5672/rabbitmq_vhost
      - BACKEND_URL=http://backend-app:5000
    ports:
      - "5001:5001"
    volumes:
      - ./helge-api:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq-consumer:
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    command: python -u app/rabbitmq_consumer.py
    volumes:
      - ./rabbitmq:/app
    links:
      - rabbitmq
      - backend-app
    depends_on:
      - rabbitmq


  rabbitmq:
    image: rabbitmq
    ports:
    - "5672:5672"
