version: '3.5'
services:

  helge-api:
    image: hnclonecphb/http-api:master
    environment:
      - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - BACKEND_URL=http://backend:5000
    ports:
      - 5001:5001
    depends_on:
      - backend
      - rabbitmq
    networks:
      - hackernews_ops

  frontend-app:
    image: hnclonecphb/frontend:master
    ports:
      - 3000:3000
    networks:
      - hackernews_ops
  
  backend:
    image: hnclonecphb/backend:master
    ports:
      - 5000:5000
    networks:
      - hackernews_ops
      - elk

  database:
    image: hnclonecphb/database:master
    ports:
      - 27017:27017
    networks:
      - hackernews_ops

  rabbitmq:
    image: hnclonecphb/rabbitmq-docker:master
    ports:
      - 5672:5672
    networks:
      - hackernews_ops
   
  rabbitmq-consumer:
    image: hnclonecphb/rabbitmq-consumer:master
    environment:
      - rabbitmq=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - helge-api
    networks:
      - hackernews_ops

networks:
  hackernews_ops:
    name: hackernews_ops
    driver: bridge
  elk:
    name: elk
    driver: bridge
