version: '3.5'
services:
  
  helge-api:
    build: 
      context: ./helge-api
      dockerfile: Dockerfile
    command: python app/helge-api.py  
    ports:
      - "5001:5001"
    volumes:
      - ./helge-api:/app
    links:
      - database  
      - rabbitmq
      

  frontend-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-app
      - /frontend-app/node_modules
    links:
      - backend-app
  
  backend-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python -u app/api.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - database

  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/testdata:/testdata

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672