version: '3'
services:
  backend-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python -u app/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - db
  db:
    image: mongo
  frontend-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-app
      - /frontend-app/node_modules
  